package utils

// Define route constants
const (
	PatientSignupForm           = "/patient_signup_form"
	PatientSignupSteps          = "/patient_signup_steps"
	PatientSignupSubmit         = "/patient_signup_submit"
	PatientLoginScreen          = "/patient_login_screen"
	PatientLoginSubmit          = "/patient_login_submit"
	PatientDashboard            = "/patient_dashboard"
	PatientAppointments         = "/patient_appointments"
	PatientVerifyNew            = "/verify_patient"
	PatientVerifyExisting       = "/verify_existing_patient"
	PatientNewPassword          = "/patient_create_new_password"
	PatientForgotPasswordScreen = "/patient_forgot_password"
	PatientForgotPasswordSubmit = "/patient_forgot_password_submit"
	DoctorSignupForm            = "/doctor_signup_form"
	DoctorSignupSteps           = "/doctor_signup_steps"
	DoctorSignupSubmit          = "/doctor_signup_submit"
	DoctorLoginScreen           = "/doctor_login_screen"
	DoctorLoginSubmit           = "/doctor_login_submit"
	DoctorDashboard             = "/doctor_dashboard"
	DoctorAppointments          = "/doctor_appointments"
	DoctorForgotPasswordScreen  = "/doctor_forgot_password"
	DoctorForgotPasswordSubmit  = "/doctor_forgot_password_submit"
	DoctorVerifyNew             = "/verify_doctor"
	DoctorVerifyExisting        = "/verify_existing_doctor"
	DoctorNewPassword           = "/doctor_create_new_password"
	HomeLogin                   = "/login"
	HomeSignup                  = "/signup"
	GenerateCaptcha             = "/generate_captcha"
	VerifyCaptcha               = "/verify_captcha"
)
