package utils

// Define route constants
const (
	PatientSignupForm           = "/patient_signup_form"
	PatientSignupSteps          = "/patient_signup_steps"
	PatientSignupSubmit         = "/patient_signup_submit"
	PatientLoginScreen          = "/patient_login_screen"
	PatientLoginSubmit          = "/patient_login_submit"
	PatientDashboard            = "/patient_dashboard"
	PatientAppointments         = "/patient_appointments"
	PatientProfile              = "/patient_profile"
	PatientVerifyNew            = "/verify_patient"
	PatientVerifyExisting       = "/verify_existing_patient"
	PatientNewPassword          = "/patient_create_new_password"
	PatientForgotPasswordScreen = "/patient_forgot_password"
	PatientForgotPasswordSubmit = "/patient_forgot_password_submit"
	DoctorSignupForm            = "/doctor_signup_form"
	DoctorSignupSteps           = "/doctor_signup_steps"
	DoctorSignupSubmit          = "/doctor_signup_submit"
	DoctorLoginScreen           = "/doctor_login_screen"
	DoctorLoginSubmit           = "/doctor_login_submit"
	DoctorDashboard             = "/doctor_dashboard"
	DoctorAppointments          = "/doctor_appointments"
	DoctorProfile               = "/doctor_profile"
	DoctorForgotPasswordScreen  = "/doctor_forgot_password"
	DoctorForgotPasswordSubmit  = "/doctor_forgot_password_submit"
	DoctorVerifyNew             = "/verify_doctor"
	DoctorVerifyExisting        = "/verify_existing_doctor"
	DoctorNewPassword           = "/doctor_create_new_password"
	HomeLogin                   = "/login"
	HomeSignup                  = "/signup"
	AdminLoginScreen            = "/admin_login"
	AdminLoginSubmit            = "/admin_login_submit"
	AdminDashboard              = "/admin_dashboard"
	AdminProfile                = "/admin_profile"
	AdminCreate                 = "/admin_create"
	AdminCreateSubmit           = "/admin_create_submit"
	AdminSetCredentials         = "/admin_set_credentials"
	AdminRegisterSubmit         = "/admin_register_submit"
	AdminViewDoctorList         = "/admin_view_doctor_list"
	AdminViewPatientList        = "/admin_view_patient_list"
	AdminAppointments           = "/admin_view_appointments"
	MasterAdminLoginScreen      = "/master_admin_login"
	MasterAdminLoginSubmit      = "/master_admin_login_submit"
	GenerateCaptcha             = "/generate_captcha"
	VerifyCaptcha               = "/verify_captcha"
)

// Domain name
const InternalDomain = "internal.ordindia.foundation"
const PublicDomain = "ordindia.foundation"
